### ISSUE TITLE
Docker Container?

### ISSUE THREAD

**Issue by CameronTStark** [bemoss/BEMOSS3.5#35]
I've gone through the installation procedure a few times and the steps seem to lend themselves nicely to making a Docker container. It would be particularly useful since it shouldn't need the the Ubuntu VM anymore and be more platform agnostic. Has anyone from your team tried this?

If not, I'd be happy to give it a shot if I can get some support on the steps it takes to set everything up.

**Comment by pratapme1** [comment]
Hi, I am getting the following area while starting BEMOSS for first time. Please help me to solve this.not starting rpc server as requested..Use JMX (storageServices->startRPCServer()) or nodetool(enablethrift) to start it

**Comment by CameronTStark** [comment]
@pratapme1 You've double posted your request, once in this issue that I've open and one for yourself. I suggest you delete the one in this issue so yours can be handled separately, thanks.

**Comment by zxymark221** [comment]
Great, please go ahead and test. Our team hasn't tried this before. Please let us know what support you will need.

**Comment by CameronTStark** [comment]
I've done an initial trial of building a Docker container for BEMOSS3.5 but because of the GUI interface used during installation it doesn't work out of the box. I've tried to "translate" GUI/bemoss_install_v3.5.sh to a Dockerfile butthere's particulars about the install, such as the use of root, that makes doing this myself a painful trial-and-error process. 

It would be easier if someone familiar with the initialization sequence could help me arrive at a distilled environment by helping me collect the following:

* all apt-get install packages
* all environment variables
* pip install packages
* non-default config files (for Cassandra, etc.)
* startup script(s) 

If there are separate processes running concurrently, and it looks like there are from the multiple terminals running after a successful install, we can create individual containers and link them together as one package. If this is the case I'd need the pip packages, apt-packages, config files, etc. separated out for each individual process running. 

My hope is that this is easy, or at least isn't horrible, for people in the dev team to do; for me, I'm getting into BEMOSS and could use this functionality but I'm really focused elsewhere.

The end product would be a downloadable container that would need virtually no setup to run, be more easily customizable in a < 1GB footprint and should make adoption of BEMOSS3.5 focused on the configuration.  

Can you and/or others spare the time to help me do this?

**Comment by diptendutan** [comment]
Hello There,
We are trying to create docker file of BMEOSS3.5 application by referring the install scrips but no luck.Could someone have successfully dockerize the application? If so, could you please help us on that.
Attaching the error that we got while building the docker file out of install script.
![image](https://user-images.githubusercontent.com/49410559/83245609-9d1cf400-a1be-11ea-84e8-b4454e638551.png)
