### ISSUE TITLE
RPC Server Not starting

### ISSUE THREAD

**Issue by pratapme1** [bemoss/BEMOSS3.5#36]
Hi, I am getting the following errorvwhile starting BEMOSS for first time. Please help me to solve this.not starting rpc server as requested..Use JMX (storageServices->startRPCServer()) or nodetool(enablethrift) to start it

**Comment by rajeee** [comment]
Please ask the question in the support forum at https://groups.google.com/forum/#!forum/bemoss. 
Make sure to include full details and screenshots. 
Thanks

**Comment by Raagu1993** [comment]
May I know where is the solution for this issue? Even i am facing same issue
