### ISSUE TITLE
Finding errors while trying to run the BEMOSS server

### ISSUE THREAD

**Issue by mohantysubhendu** [bemoss/BEMOSS3.5#40]
After successfully installing the BEMOSS3.5 software, when  I am trying to run the BEMOSS it is throwing errors.
I have mentioned the errors below kindly help me on these issues.

AttributeError: 'module' object has no attribute 'core'
AttributeError: 'gevent._event.AsyncResult' object has no attribute 'ident'

**Comment by akshaygepl1** [comment]
Have checked all the libraries are installed properly still facing the issue.

**Comment by mohantysubhendu** [comment]
I have checked all the libraries inside BEMOSS_requirements.txt
Execpt #pyOpenSSL==0.13.1 everything showing installed properly.
Can you help me  to install this #pyOpenSSL==0.13.1

**Comment by rajeee** [comment]
This is a recent development and we have been able to reproduce the error. We are working on a solution.

**Comment by mohantysubhendu** [comment]
Ok, please revert back once you get the solution.

**Comment by akshaygepl1** [comment]
Kindly install gevent ==1.2.2 the above issue will be solved.

**Comment by mohantysubhendu** [comment]
I have installed gevent 1.2.2 version still its giving the same issue,
![bemoss_error](https://user-images.githubusercontent.com/38078924/40649020-7e09400c-634d-11e8-83ce-7aaedfd88ef8.png)

**Comment by akshaygepl1** [comment]
Which version of gevent you have outside the virtualenv.

**Comment by mohantysubhendu** [comment]
Thankyou so much, I am able to find the BEMOSS dashboard now.

**Comment by mohantysubhendu** [comment]
Added a line `gevent==1.2.2` in BEMOSS_requirements.txt and ran the command `pip install -r BEMOSS_requirements.txt`.
BEMOSS is running now. Thank you
