### ISSUE TITLE
Unable to start BEMOSS

### ISSUE THREAD

**Issue by mohantysubhendu** [bemoss/BEMOSS3.5#41]
I have setup.py in all the agent folder, still it's asking this
--> Agent directory must have a setup.py in it.
Please tell me Where to put setup.py to resolve this issue
![bemoss_agent](https://user-images.githubusercontent.com/38078924/40423707-f8b876f2-5eb0-11e8-9c33-7d1d15eea481.png)

**Comment by akshaygepl1** [comment]
How did you eliminate the below error:

AttributeError: 'gevent._event.AsyncResult' object has no attribute 'ident'

**Comment by akshaygepl1** [comment]
Remove everything and clean install once again, the issue is caused due to different version of libraries.

**Comment by mohantysubhendu** [comment]
Are you able to see the bemoss dashboard now?

**Comment by akshaygepl1** [comment]
Yes

**Comment by mohantysubhendu** [comment]
Attribute error also gone?

**Comment by akshaygepl1** [comment]
Yes I have given the solution in the #40

**Comment by akshaygepl1** [comment]
Close this one @mohantysubhendu .

**Comment by mohantysubhendu** [comment]
The solution to this issue is in https://github.com/bemoss/BEMOSS3.5/issues/40
