### ISSUE TITLE
Run BEMOSS

### ISSUE THREAD

**Issue by Raagu1993** [bemoss/BEMOSS3.5#47]
After installing BEMOSS , when I try to run BEMOSS following errors are coming. can any one help me on this.
![image](https://user-images.githubusercontent.com/20613013/50635170-15a26580-0f77-11e9-8812-b2dad12d6022.png)

**Comment by ashrafulhaque99** [comment]
I know it's late. But if you are still trying and still seeing this error message please look at your  "parent_ip.txt" file and check whether the IP is the same as your current network IP. If your wifi/LAN does not have a fixed IP; you need to change the parent_IP.txt file each time it gets changed. Also remember to change the postgres config files as mentioned in setup process in wiki in post installation setup steps. Restart bemoss and it should work.
